import Head from "next/head"
import styles from "./styles.module.scss"

const AuthLayout: React.FC<React.PropsWithChildren> = (props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="_container">
        <main className={styles.page}>
          <div className={styles.wrapper}>{props.children}</div>
        </main>
      </div>
    </>
  )
}

export default AuthLayout
