import Head from "next/head"
import styles from "./styles.module.scss"

type AuthLayoutProps = {
  title?: string
}

const AuthLayout: React.FC<React.PropsWithChildren<AuthLayoutProps>> = (
  props
) => {
  return (
    <>
      <Head>
        <title>{props.title ?? "Авторизация"}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="_container">
        <main className={styles.page}>
          <div className={styles.wrapper}>{props.children}</div>
        </main>
      </div>
    </>
  )
}

export default AuthLayout
