import Head from "next/head"

const AuthLayout: React.FC<React.PropsWithChildren> = (props) => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <main className="grid min-h-[100svh] place-items-center py-safe-area">
          <div className="grid place-items-center rounded-medium-shape bg-surface-container p-8">
            {props.children}
          </div>
        </main>
      </div>
    </>
  )
}

export default AuthLayout
