import Head from "next/head"
import { useRouter } from "next/router"
import { useEffect } from "react"
import Header from "~/components/Header"
import Sidebar from "~/components/Sidebar"
import { useAuthStore } from "~/store/auth"
import { api } from "~/utils/api"
import { PagePaths } from "~/utils/enums"
import { cls } from "~/utils/helpers"
import styles from "./styles.module.scss"

type MainLayoutProps = {
  title?: string
}

const MainLayout: React.FC<React.PropsWithChildren<MainLayoutProps>> = (
  props
) => {
  const authStore = useAuthStore()
  const router = useRouter()

  const currentUserQuery = api.user.getCurrent.useQuery(undefined, {
    retry: false,
  })

  useEffect(() => {
    if (!currentUserQuery.isLoading && currentUserQuery.error)
      return void router.push(PagePaths.SignIn)

    if (currentUserQuery.data) authStore.setUser(currentUserQuery.data)
  }, [
    currentUserQuery.data,
    currentUserQuery.error,
    currentUserQuery.isLoading,
    router,
  ])

  return (
    <>
      <Head>
        <title>{props.title ?? "Workflow"}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <div className={cls([styles.layout, "_container"])}>
        <Header />
        {props.children}
      </div>
    </>
  )
}

export default MainLayout
